FROM cakebuild/cake:sdk-7.0 AS build
WORKDIR /src

COPY WeatherApi/ .

RUN dotnet cake

FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine
WORKDIR /final
COPY --from=build /out .

ENTRYPOINT ["dotnet", "WeatherApi.dll"]